### ISSUE TITLE
Microsoft offer

### ISSUE THREAD

**Issue by toanehihi** [khoakomlem/socketio-mq#2]
![images (2)](https://github.com/khoakomlem/socketio-mq/assets/134390104/5645b381-04e0-4bb7-9e1b-6ec569730490)

**Comment by beanbocchi** [comment]
Imma ignoring this

**Comment by downgear** [comment]
https://github.com/khoakomlem/socketio-mq/assets/134379113/67ef8195-f4d6-45af-aa96-e11313b49a01
